module Blueprint::HTML
  register_element :a
  register_element :abbr
  register_element :address
  register_element :article
  register_element :aside
  register_element :audio
  register_element :b
  register_element :bdi
  register_element :bdo
  register_element :blockquote
  register_element :body
  register_element :button
  register_element :canvas
  register_element :caption
  register_element :cite
  register_element :code
  register_element :colgroup
  register_element :data
  register_element :datalist
  register_element :dd
  register_element :del
  register_element :details
  register_element :dfn
  register_element :dialog
  register_element :div
  register_element :dl
  register_element :dt
  register_element :em
  register_element :fieldset
  register_element :figcaption
  register_element :figure
  register_element :footer
  register_element :form
  register_element :h1
  register_element :h2
  register_element :h3
  register_element :h4
  register_element :h5
  register_element :h6
  register_element :head
  register_element :header
  register_element :hgroup
  register_element :html
  register_element :i
  register_element :ins
  register_element :kbd
  register_element :label
  register_element :legend
  register_element :li
  register_element :main
  register_element :map
  register_element :mark
  register_element :menu
  register_element :meter
  register_element :nav
  register_element :noscript
  register_element :object
  register_element :ol
  register_element :optgroup
  register_element :option
  register_element :output
  register_element :p
  register_element :picture
  register_element :pre
  register_element :progress
  register_element :q
  register_element :rp
  register_element :rt
  register_element :ruby
  register_element :s
  register_element :samp
  register_element :script
  register_element :section
  register_element :select_tag, "select"
  register_element :slot
  register_element :small
  register_element :span
  register_element :strong
  register_element :style
  register_element :sub
  register_element :summary
  register_element :sup
  register_element :table
  register_element :tbody
  register_element :td
  register_element :template
  register_element :textarea
  register_element :tfoot
  register_element :th
  register_element :thead
  register_element :time
  register_element :title
  register_element :tr
  register_element :u
  register_element :ul
  register_element :var
  register_element :video

  register_void_element :area
  register_void_element :base
  register_void_element :br
  register_void_element :col
  register_void_element :embed
  register_void_element :hr
  register_void_element :img
  register_void_element :input
  register_void_element :link
  register_void_element :meta
  register_void_element :source
  register_void_element :track
  register_void_element :wbr

  register_empty_element :iframe
  register_empty_element :portal
end
