name: CI
on:
  push:

jobs:
  ci:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v4

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1

      - name: Run tests
        run: crystal spec

      - name: Cache Shards
        uses: actions/cache@v3
        with:
          path: |
            ./lib
            ./bin
          key: shards-${{ hashFiles('shard.yml') }}

      - name: Install shards
        run: shards install

      - name: Check code format
        run: crystal tool format --check

      - name: Lint with ameba
        run: bin/ameba
